package com.epam.training.treasury.beans.clothes;

public enum ClothesTagElement {
	TITLE, MATERIAL, TYPE, PRICE, HEAD_PROTECTION, HEAD_GIRTH, BODY_PROTECTION, SHOULDER_GIRTH, 
	BODY_GIRTH, PICTURE, LEG_PROTECTION, LEG_GIRTH, FOOT_GIRTH;
}